version: "3.9"

services:
  php74:
    image: php8.1-fpm-alpine
    container_name: php81
    hostname: php81
    user: 1000:1000
    networks:
      - server-network
    volumes:
      - /home/nikita/Projects:/projects

networks:
  server-network:
    external: true
