version: "3.9"

services:
  php73:
    image: php7.2-fpm-alpine
    container_name: php72
    hostname: php72
    user: 1000:1000
    networks:
      - server-network
    volumes:
      - /home/nikita/Projects:/projects

networks:
  server-network:
    external: true
