version: "3.9"

services:
  redis:
    container_name: redis
    hostname: redis
    networks:
      - server-network
    image: redis
    ports:
      - 6379:6379
    command: ["sh", "-c", "exec redis-server --requirepass \"password\""]

networks:
  server-network:
    external: true
